#!/bin/bash
set -e

if [ -z "$2" ]; then
	PATTERN=.
else
	PATTERN=$2
fi

SNAPSHOTS=`zfs list -r -H -t snapshot $1 |grep "$PATTERN"| cut -f 1`
echo "The following snapshots will be removed:"
echo
echo "$SNAPSHOTS" | tr ' ' '\n'
echo
echo "Hit ctrl-c to cancel, or enter to proceed"
read DUMMY

for snapshot in $SNAPSHOTS
do
	echo "destroying $snapshot"
	zfs destroy $snapshot
done

